const gridRef = document.querySelector(".grid-content");
new gridjs.Grid({
    columns: [
        {
            id: "myCheckbox",
            name: "Select",
            plugin: {
                // install the RowSelection plugin
                component: gridjs.plugins.selection.RowSelection,
                // RowSelection config
                props: {
                    // use the *any column as the row identifier
                    // for Eg: use contract -- row.cell(1).data
                    // Or you can use two cell,
                    // Eg: contract + issuance date -- row.cell(1).data + row.cell(3).data
                    id: (row) => row.cell(1).data,
                },
                // ***Note: selection feature requires an unique identifier for every row
                // ***Eg: ID, email, SSN, etc.,
                // ****** In our case, empty strings are not unique that's why
                // ****** we have numbered the contacts, you can remove that numbering
                // ****** when you confidential data

                // *Grid will properly work when it contains data, so I have added some fake data*
            },
        },
        "Contract",
        "Issuance",
        "Issuance Date",
        "Gross Proceeds",
        "Bank Deposit",
        "Upfront Fees",
        "Fee Basis",
        "Maturity Date",
        "Original Term",
        "Remaining Term",
        "Daily Accural to PAR",
        "PAR Maturity",
        "Rate",
        "Days Convention",
        "Bank/Dealer",
        "Purchaser",
        "Status",
    ],
    data: [
        // Data cannot be empty, so we have used empty strings
        [
            "1",
            "Ziya",
            "28/05/1999",
            "100",
            "2,99,999/-",
            "5,999/-",
            "monthly",
            "28/05/2014",
            "25 years",
            "2 years",
            "500/-",
            "50,000/-",
            "1,999/-",
            "5",
            "Bank",
            "Ziya",
            "Active",
            "",
        ],
        [
            "2",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        ],
        [
            "3",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        ],
        [
            "4",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        ],
        [
            "5",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        ],
        [
            "6",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        ],
        [
            "7",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        ],
    ],
    pagination: {
        limit: 10,
    },
    resizable: true,
    sort: true,
    style: {
        th: {
            "background-color": "rgb(170, 170, 170)",
            color: "#000",
            "border-bottom": "3px solid #ccc",
            "text-align": "center",
            "min-width": "200px",
        },
        td: {
            "text-align": "center",
            "min-width": "200px",
        },
    },
}).render(gridRef);
